apiVersion: v1
kind: Service
metadata:
  name: solvers-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: solvers-mysql
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: solvers-mysql
spec:
  selector:
    matchLabels:
      app: solvers-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: solvers-mysql
    spec:
      containers:
      - image: mysql:8.0.27
        name: solvers-mysql
        env:
        - name: MYSQL_DATABASE
          value: dev
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        ports:
        - containerPort: 3306
          name: solvers-mysql
        volumeMounts:
        - name: solvers-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: solvers-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: solvers-mysql-pv-claim
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: solvers-mysql-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solvers-mysql-pv-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi